<a href="https://colab.research.google.com/github/nachopodesta/numpy-for-data-science/blob/main/NumPy_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy for Data Science Beginners: 2021


https://www.udemy.com/course/the-complete-numpy-course-for-data-science/learn/lecture/24287378#overview

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [3]:
from numpy import array

In [4]:
np.random.randint(2,10)

9

In [5]:
print(np.__version__)

1.21.6


In [6]:
sample = np.random.randint(0,100,20000000)
sample

array([29, 52, 34, ..., 16,  8, 80])

In [7]:
%timeit np.power(sample,2)

52 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
arr = np.array([1,2,3,4,5])
print(arr.shape)
print(type(arr))

(5,)
<class 'numpy.ndarray'>


In [9]:
a = np.array([12])
a.ndim

1

In [10]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.ndim

3

In [11]:
arr = np.array([1,2,3,4,5],ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5]]]]])

In [12]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c.shape

(2, 4)

In [13]:
a = np.array([[1,2,3],[4,5,6]])
a.shape 

(2, 3)

In [14]:
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[0,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12]])

In [16]:
b = a.reshape(2,3,2)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9,  0],
        [11, 12]]])

In [17]:
arr = np.array([1,2,3,4,5], dtype = 'int16')
arr

array([1, 2, 3, 4, 5], dtype=int16)

In [18]:
arr.itemsize

2

In [19]:
arr.size * arr.itemsize

10

In [20]:
arr = np.array([1,2,3,4,5], dtype = 'f2')
arr

array([1., 2., 3., 4., 5.], dtype=float16)

In [21]:
arr = np.array([1,2,3,4,5], dtype = 'complex')
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [22]:
arr = np.array([1.1,2.2,3.3])
cv = arr.astype('i')
cv

array([1, 2, 3], dtype=int32)

### 6. Index & Slice

In [23]:
arr = np.array([1,2,3,4,5])
arr[1]

2

In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr[1,1]

7

In [25]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[0,1,1]

5

In [26]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr[1,-2]

9

In [27]:
arr = np.array([1,2,3,4,5])
arr[1:4]

array([2, 3, 4])

In [31]:
arr = np.array([1,2,3,4,5])
arr[1:3]

array([2, 3])

In [32]:
arr = np.array([1,2,3,4,5,6,7])
arr[4:]

array([5, 6, 7])

In [37]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
arr[:,4]

array([ 5, 13])

In [38]:
arr[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr[0,1:6:2]

array([2, 4, 6])

In [40]:
arr[0,2] = 2000
arr

array([[   1,    2, 2000,    4,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16]])

In [41]:
arr[0,1:4] = 3000
arr

array([[   1, 3000, 3000, 3000,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16]])

In [42]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
arr[:,2] = [4000,6000]
arr

array([[   1,    2, 4000,    4,    5,    6,    7,    8],
       [   9,   10, 6000,   12,   13,   14,   15,   16]])

In [47]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print('\n')
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6


In [48]:
arr[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [50]:
arr[:,1,:] = [[9,9,9],[8,8,8]]
arr

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

In [51]:
arr = np.array([1,2,3,4,5,6,7])
arr[:4]

array([1, 2, 3, 4])

In [52]:
arr[-3:-1]

array([5, 6])

In [53]:
arr[1:5:2]

array([2, 4])

In [54]:
arr[::2]

array([1, 3, 5, 7])

In [55]:
arr = np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[1,1:4]

array([7, 8, 9])

In [56]:
arr[0:2,2]

array([3, 8])

In [57]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])